---
title: "Chrisler_Assignment_2"
author: "Brett Chrisler"
date: "March 5, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r readRDS provided<-TRUE}
precip <- readRDS("USAAnnualPcpn1950_2008.rds")
temp <- readRDS("USAAnnualTemp1950_2008.rds")

```

```{r Remove NA values}
#p for precip and t for temperature
df.list <- list(precip,temp)
nans <- lapply(df.list, function(x) x[complete.cases(x),])
```

```{r Aggregation}
agg <- lapply(nans, function(x) aggregate(year ~ lat+lon+name, x, FUN=length))
```

```{r Minimum amout of years}
min = 40
vars <- c("lat","lon","name")
subset <- lapply(agg, function(x) subset(x, year >= min))
filt <- lapply(subset, function(x) unique(x[vars]))
```

```{r Data for stations left}
vars <- c("lat","lon","name")
p_filt <- merge(precip,filt[1], by=c(vars))
t_filt <- merge(temp, filt[2], by=c(vars))
sorted <- p_filt[ order(p_filt[,1],p_filt[,2], p_filt[,6]),]
```


```{r split by data points including NA values}
years <- 59
sorted_num <- sorted[,-3:-4]
d <- split(sorted_num, (seq(nrow(p_filt))-1) %/% years)
m <- as.matrix(d)
l <- lapply(m, function(x) lm(data~year, data=x))
slopes <- lapply(l, function(x) (x$coefficients["year"]))

```