---
title: "Proposal"
author: "Brett Chrisler"
date: "April 9, 2018"
output:
  html_document:
    df_print: paged
bibliography: Bibliography.xml
---

# __Comparing Indices: Madden-Julian Oscillation and Termination__

### I. Motivation
The Madden - Julian Oscillation (MJO) is a large-scale circulation that is occasionally coupled with convection. The MJO propagates eastward at around 5 m/s and has an intraseasonal lifespan of 30 - 90 days. The MJO most often begins in the Indian Ocean and ends in the Western Pacific; however, location can vary immensely and is divided into eight phases. There are two modes of the MJO which are active and inactive. During the active mode, strong convection prevails and higher precipitation amounts are observed, while the inactive mode. To analyze the length of an active mode, indices are created to set a threshold of when the MJO is either mode [@Zhang2005].

Comparing these indices to see how they do well with recognizing the active mode, as well as when an event is terminated is crucial for the study of the Madden-Julian Oscillation. The birth and decay of the MJO is still unknown and comparing indices could shine light on what precursor conditions allow for the MJO to maintain itself. As the MJO has widespread impacts on global climate, understanding this phenomena is important especially in regards to global climate models (GCMs).
<br>

### II. Data and Analysis
Multiple indcies exist for the Madden-Julian Oscillation with the most used being the Real-time Multivariate MJO (RMM) index. This index uses both OLR and zonal winds to calcuate the principal components and amplitude of the MJO. Additional indices include the following: the OLR MJO Index, OMI, the Original OLR MJO Index, OOMI, the Real-time OLR MJO Index, RMP, the Filtered OLR MJO index, FMO, and the Velocity Potential MJO index, VPM. OMI, OOMI, RMO, and FMO are univariate and use OLR data, while the VPM is multivariate like the RMM but instead used 200 hPa velocity potentional instead of OLR. 
<br>

### III. Expected Results
Results should at least be consistent among filters using similar methods, such as all OLR univariate indices should return similar results. Variations may occur due to different filtering among the indices. If multivariate results return similar results to the univariate ones, then it should indicate that the additional parameter is not necessarily important for maintaining an MJO event. Additionally, the length of an event will be a good indicator if a certain index is picking up on a known case study event.